config/routes.rb
Rails.application.routes.draw do

  root to: "donations#index"
  resources :donations
  resources :donors

end

app/models/donation.rb
class Donation < ActiveRecord::Base
  belongs_to :donor
  validates_presence_of :amount, :date
  validates_numericality_of :amount, :greater_than_or_equal_to => 0.01

  validate :date_donation_cannot_be_in_the_future

  def date_donation_cannot_be_in_the_future
    errors.add(:date, "can't be in the future") if !date.blank? and date > Date.today
  end

end

app/models/donor.rb
class Donor < ActiveRecord::Base
  has_many :donations
  validates_presence_of :name, :email
  validates_length_of :name, :minimum => 2
  validates_uniqueness_of :name

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_donation, only: [:show, :edit, :update, :destroy]

  # GET /donations
  # GET /donations.json
  def index
    @donations = Donation.all
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
  end

  # GET /donations/new
  def new
    @donation = Donation.new
  end

  # GET /donations/1/edit
  def edit
  end

  # POST /donations
  # POST /donations.json
  def create
    @donation = Donation.new(donation_params)

    respond_to do |format|
      if @donation.save
        format.html { redirect_to @donation, notice: 'Donation was successfully created.' }
        format.json { render :show, status: :created, location: @donation }
      else
        format.html { render :new }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donations/1
  # PATCH/PUT /donations/1.json
  def update
    respond_to do |format|
      if @donation.update(donation_params)
        format.html { redirect_to @donation, notice: 'Donation was successfully updated.' }
        format.json { render :show, status: :ok, location: @donation }
      else
        format.html { render :edit }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation.destroy
    respond_to do |format|
      format.html { redirect_to donations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation = Donation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donation_params
      params.require(:donation).permit(:donor_id, :amount, :date)
    end
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
  before_action :set_donor, only: [:show, :edit, :update, :destroy]

  # GET /donors
  # GET /donors.json
  def index
    @donors = Donor.all
  end

  # GET /donors/1
  # GET /donors/1.json
  def show
  end

  # GET /donors/new
  def new
    @donor = Donor.new
  end

  # GET /donors/1/edit
  def edit
  end

  # POST /donors
  # POST /donors.json
  def create
    @donor = Donor.new(donor_params)

    respond_to do |format|
      if @donor.save
        format.html { redirect_to @donor, notice: 'Donor was successfully created.' }
        format.json { render :show, status: :created, location: @donor }
      else
        format.html { render :new }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donors/1
  # PATCH/PUT /donors/1.json
  def update
    respond_to do |format|
      if @donor.update(donor_params)
        format.html { redirect_to @donor, notice: 'Donor was successfully updated.' }
        format.json { render :show, status: :ok, location: @donor }
      else
        format.html { render :edit }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donors/1
  # DELETE /donors/1.json
  def destroy
    @donor.destroy
    respond_to do |format|
      format.html { redirect_to donors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donor
      @donor = Donor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donor_params
      params.require(:donor).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/views/donations/_form.html.erb
<%= form_for(@donation) do |f| %>
  <% if @donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
      <% @donation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :donor_id %><br>
      <%= f.collection_select :donor_id, Donor.all, :id, :name, :prompt => true %>
    </div>

  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/donations/edit.html.erb
<h1>Editing donation</h1>

<%= render 'form' %>

<%= link_to 'Show', @donation %> |
<%= link_to 'Back', donations_path %>

app/views/donations/index.html.erb
<h1>Listing donations</h1>

<table>
  <thead>
    <tr>
      <th>Donor</th>
      <th>Amount</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @donations.each do |donation| %>
      <tr>
        <td><%= donation.donor.name %></td>
        <td><%= number_to_currency(donation.amount) %></td>
        <td><%= (donation.date).strftime("%B %d, %Y") %></td>
        <td><%= link_to 'Show', donation %></td>
        <td><%= link_to 'Edit', edit_donation_path(donation) %></td>
        <td><%= link_to 'Delete', donation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  </tbody>
</table>
<br>

<b>Data as of: <%= (Date.today).strftime("%B %d, %Y") %></b><br>
<b>Total donations made: <%= Donation.count("id") %></b><br>
<b>Total Donated: <%= number_to_currency(Donation.sum(:amount))%></b><br>


<br>

<%= link_to 'New Donation', new_donation_path %>

app/views/donations/new.html.erb
<h1>New donation</h1>

<%= render 'form' %>

<%= link_to 'Back', donations_path %>

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Donor:</strong>
  <%= @donation.donor.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= number_to_currency(@donation.amount) %>
</p>

<p>
  <strong>Date:</strong>
  <%= (@donation.date).strftime("%B %d, %Y") %>
</p>

<%= link_to 'Edit', edit_donation_path(@donation) %> |
<%= link_to 'Back', donations_path %>

app/views/donors/_form.html.erb
<%= form_for(@donor) do |f| %>
  <% if @donor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donor.errors.count, "error") %> prohibited this donor from being saved:</h2>

      <ul>
      <% @donor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/donors/edit.html.erb
<h1>Editing donor</h1>

<%= render 'form' %>

<%= link_to 'Show', @donor %> |
<%= link_to 'Back', donors_path %>

app/views/donors/index.html.erb
<h1>Listing donors</h1>

<table>
  <thead>
    <tr>
      <th>Donor's Name</th>
      <th>Donor's Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @donors.each do |donor| %>
      <tr>
        <td><%= donor.name %></td>
        <td><%= donor.email %></td>
        <td><%= link_to 'Show', donor %></td>
        <td><%= link_to 'Edit', edit_donor_path(donor) %></td>
        <td><%= link_to 'Delete', donor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Donor', new_donor_path %>

app/views/donors/new.html.erb
<h1>New donor</h1>

<%= render 'form' %>

<%= link_to 'Back', donors_path %>

app/views/donors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @donor.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @donor.email %>
</p>


<table>
  <thead>
  <tr>
    <th>Donation Amount</th>
    <th>Donation Date</th>
  </tr>
  </thead>


  <p>
    <strong>Donations by this person:</strong>

    <tbody>
    <% @donor.donations.each do |b| %>
        <tr>
          <td> <%= number_to_currency(b.amount)%> </td>
          <td> <%= (b.date).strftime("%B %d, %Y") %> </td>
    <% end %>
    </tr>
    </tbody>
</table>
<br>
<b>Total Donated by this person:
<%= number_to_currency(Donation.where("donor_id =?", params[:id]).sum(:amount)) %></b>
<br>
<br>

<%= link_to 'Edit', edit_donor_path(@donor) %> |
<%= link_to 'Back', donors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<ul>
  <li><%= link_to "Donors", donors_path %></li>
  <li><%= link_to "Donations", donations_path %></li>
</ul>

<head>
  <title>Donations</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>